# Generated by Django 4.2.6 on 2023-12-08 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dept',
            fields=[
                ('deptno', models.IntegerField(max_length=5, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=100)),
                ('Loc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.IntegerField()),
                ('ename', models.CharField(max_length=100)),
                ('sal', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('deptno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
            ],
        ),
    ]
