# Generated by Django 4.2.6 on 2023-12-08 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dept_emp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='deptno',
        ),
        migrations.DeleteModel(
            name='dept',
        ),
        migrations.DeleteModel(
            name='emp',
        ),
    ]
